version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
      - yarn-cache:/home/www-data/.cache/yarn/v1:cached
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql:cached
    networks:
      - laravel

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data:cached
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  yarn-cache:
